from pydantic import BaseModel, Field
from typing import Annotated, Literal
from operator import add



class AgentSchema(BaseModel): #Backbone of the agent, agent will perform well if the input is structured in this format
    message : Annotated[list,add]= Field(..., description="List of messages to be processed by the agent.")
    curated_ques : str = Field(..., description="Curated user question")
    prompt_query_context : str = Field(..., description="A detailed prompt with SQL DB context that will help agent to generate SQL query")
    is_safe : Literal["Yes", "No"] = Field(..., description="Indicates whether the generated SQL query is safe to execute or not.")
    generated_sql_query : str = Field(..., description="The SQL query generated by the agent based on the provided messages and context.")
    sql_query_execution_result : str = Field(..., description="The result of executing the generated SQL query.")
    final_answer : str = Field(..., description="The final answer generated by the agent based on the SQL query execution result and the curated user question.")

